AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
